name: My first workFlow

on: push

jobs:
    first_job:
        runs-on:    ubuntu-latest
        steps: 
            - name: checkou repo
              uses: actions/checkout@v4
              
            - name: welcone message
              run: echo "My first github Action job"

            - name: List files
              run: ls

            - name: read files
              run: cat README.md
